<?xml version="1.0"?>
<package format="3">
  <name>rslidar_msg</name>
  <version>1.5.20</version>
  <description>ROS2 packet message required by RoboSense rslidar_sdk.</description>
  <maintainer email="pengbo@deeprobotics.cn">S10 integration team</maintainer>
  <license>BSD-3-Clause</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>
  <depend>std_msgs</depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
