"""Export a topometric route-submap map as a dense global XYZ PLY.

The route-map NPZ files store points in each anchor's local frame.  This tool
transforms them into the manifest coordinate frame and performs one global
voxel pass so overlapping route submaps do not overweight the prior map.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import struct

import numpy as np


def _voxel_first(points: np.ndarray, voxel_size_m: float) -> np.ndarray:
    cloud = np.asarray(points, dtype=np.float32)
    if cloud.ndim != 2 or cloud.shape[1] != 3:
        raise ValueError(f"expected Nx3 points, got {cloud.shape}")
    cloud = cloud[np.isfinite(cloud).all(axis=1)]
    if len(cloud) == 0:
        return np.empty((0, 3), dtype=np.float32)

    keys = np.floor(cloud.astype(np.float64) / voxel_size_m).astype(np.int32)
    key_rows = np.ascontiguousarray(keys).view(
        np.dtype((np.void, keys.dtype.itemsize * keys.shape[1]))
    ).reshape(-1)
    _, first = np.unique(key_rows, return_index=True)
    first.sort()
    return np.ascontiguousarray(cloud[first], dtype=np.float32)


def _write_xyz_ply(path: Path, points: np.ndarray) -> None:
    cloud = np.ascontiguousarray(points, dtype="<f4")
    header = (
        "ply\n"
        "format binary_little_endian 1.0\n"
        "comment generated by export_topometric_prior_map.py\n"
        f"element vertex {len(cloud)}\n"
        "property float x\n"
        "property float y\n"
        "property float z\n"
        "end_header\n"
    ).encode("ascii")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("wb") as stream:
        stream.write(header)
        stream.write(cloud.tobytes(order="C"))


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def export_prior_map(
    manifest_path: Path,
    output_path: Path,
    *,
    voxel_size_m: float = 0.10,
    points_field: str = "fine_points_anchor_m",
    batch_submaps: int = 16,
) -> dict[str, object]:
    if voxel_size_m <= 0.0:
        raise ValueError("voxel_size_m must be positive")
    if batch_submaps <= 0:
        raise ValueError("batch_submaps must be positive")

    manifest_path = manifest_path.expanduser().resolve()
    output_path = output_path.expanduser().resolve()
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    entries = manifest.get("submaps")
    if not isinstance(entries, list) or not entries:
        raise ValueError("manifest contains no submaps")

    root = manifest_path.parent
    raw_points = 0
    finite_points = 0
    batches: list[np.ndarray] = []
    pending: list[np.ndarray] = []

    for index, entry in enumerate(entries):
        submap_path = root / entry["file"]
        with np.load(submap_path) as data:
            if points_field not in data:
                raise KeyError(f"{points_field} missing from {submap_path}")
            local = np.asarray(data[points_field], dtype=np.float32)
            pose = np.asarray(data["anchor_pose"], dtype=np.float64)

        if local.ndim != 2 or local.shape[1] != 3:
            raise ValueError(f"invalid points in {submap_path}: {local.shape}")
        if pose.shape != (4, 4) or not np.isfinite(pose).all():
            raise ValueError(f"invalid anchor_pose in {submap_path}")
        if not np.allclose(pose[3], (0.0, 0.0, 0.0, 1.0), atol=1e-8):
            raise ValueError(f"non-homogeneous anchor_pose in {submap_path}")

        raw_points += len(local)
        local = local[np.isfinite(local).all(axis=1)]
        finite_points += len(local)
        world = local.astype(np.float64) @ pose[:3, :3].T + pose[:3, 3]
        pending.append(np.asarray(world, dtype=np.float32))

        if len(pending) == batch_submaps or index + 1 == len(entries):
            batch = _voxel_first(np.concatenate(pending, axis=0), voxel_size_m)
            batches.append(batch)
            pending.clear()

    points = _voxel_first(np.concatenate(batches, axis=0), voxel_size_m)
    if len(points) == 0:
        raise ValueError("export produced an empty prior map")
    _write_xyz_ply(output_path, points)

    report = {
        "schema_version": 1,
        "source_manifest": str(manifest_path),
        "source_manifest_sha256": _sha256(manifest_path),
        "coordinate_frame": manifest.get("coordinate_frame"),
        "output_ply": str(output_path),
        "output_ply_sha256": _sha256(output_path),
        "points_field": points_field,
        "voxel_size_m": voxel_size_m,
        "submap_count": len(entries),
        "raw_points": raw_points,
        "finite_points": finite_points,
        "voxel_points": len(points),
        "bounds_min_m": points.min(axis=0).astype(float).tolist(),
        "bounds_max_m": points.max(axis=0).astype(float).tolist(),
    }
    report_path = output_path.with_suffix(output_path.suffix + ".report.json")
    report_path.write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return report


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("manifest", type=Path)
    parser.add_argument("output_ply", type=Path)
    parser.add_argument("--voxel-size-m", type=float, default=0.10)
    parser.add_argument(
        "--points-field",
        choices=("points_anchor_m", "fine_points_anchor_m"),
        default="fine_points_anchor_m",
    )
    parser.add_argument("--batch-submaps", type=int, default=16)
    args = parser.parse_args()
    report = export_prior_map(
        args.manifest,
        args.output_ply,
        voxel_size_m=args.voxel_size_m,
        points_field=args.points_field,
        batch_submaps=args.batch_submaps,
    )
    print(json.dumps(report, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
